// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "LinkBaseService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class LinkBaseServiceHandler : virtual public LinkBaseServiceIf {
 public:
  LinkBaseServiceHandler() {
    // Your initialization goes here
  }

  void load_seed_by_id(const int32_t id, const bool is_add_link) {
    // Your implementation goes here
    printf("load_seed_by_id\n");
  }

  void load_seed_by_url(const std::string& seed_url, const bool is_add_link) {
    // Your implementation goes here
    printf("load_seed_by_url\n");
  }

  void get_download_task(std::vector<DownloadTask> & _return) {
    // Your implementation goes here
    printf("get_download_task\n");
  }

  void get_extract_task(std::vector<ExtractItem> & _return) {
    // Your implementation goes here
    printf("get_extract_task\n");
  }

  void upload_download_task(const DownloadedBodyItem& downloaded_body_item) {
    // Your implementation goes here
    printf("upload_download_task\n");
  }

  void upload_extract_task(const ExtractItem& extract_item, const MatchedResultItem& matched_result_item) {
    // Your implementation goes here
    printf("upload_extract_task\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<LinkBaseServiceHandler> handler(new LinkBaseServiceHandler());
  shared_ptr<TProcessor> processor(new LinkBaseServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

