/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef StaticLinkBaseService_H
#define StaticLinkBaseService_H

#include <thrift/TDispatchProcessor.h>
#include "conf_crawler_types.h"



class StaticLinkBaseServiceIf {
 public:
  virtual ~StaticLinkBaseServiceIf() {}
  virtual void load_db_task(const int32_t task_id, const bool is_add_task) = 0;
  virtual void load_mongodb_task(const int32_t task_id, const bool is_add_task) = 0;
  virtual void get_download_task(std::vector<DownloadTask> & _return) = 0;
  virtual void get_extract_task(std::vector<ExtractItem> & _return) = 0;
  virtual void get_one_extract_task(ExtractItem& _return) = 0;
  virtual void upload_download_task(const DownloadedBodyItem& downloaded_body_item) = 0;
  virtual void upload_extract_task(const ExtractItem& extract_item, const MatchedResultItem& matched_result_item) = 0;
};

class StaticLinkBaseServiceIfFactory {
 public:
  typedef StaticLinkBaseServiceIf Handler;

  virtual ~StaticLinkBaseServiceIfFactory() {}

  virtual StaticLinkBaseServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(StaticLinkBaseServiceIf* /* handler */) = 0;
};

class StaticLinkBaseServiceIfSingletonFactory : virtual public StaticLinkBaseServiceIfFactory {
 public:
  StaticLinkBaseServiceIfSingletonFactory(const boost::shared_ptr<StaticLinkBaseServiceIf>& iface) : iface_(iface) {}
  virtual ~StaticLinkBaseServiceIfSingletonFactory() {}

  virtual StaticLinkBaseServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(StaticLinkBaseServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<StaticLinkBaseServiceIf> iface_;
};

class StaticLinkBaseServiceNull : virtual public StaticLinkBaseServiceIf {
 public:
  virtual ~StaticLinkBaseServiceNull() {}
  void load_db_task(const int32_t /* task_id */, const bool /* is_add_task */) {
    return;
  }
  void load_mongodb_task(const int32_t /* task_id */, const bool /* is_add_task */) {
    return;
  }
  void get_download_task(std::vector<DownloadTask> & /* _return */) {
    return;
  }
  void get_extract_task(std::vector<ExtractItem> & /* _return */) {
    return;
  }
  void get_one_extract_task(ExtractItem& /* _return */) {
    return;
  }
  void upload_download_task(const DownloadedBodyItem& /* downloaded_body_item */) {
    return;
  }
  void upload_extract_task(const ExtractItem& /* extract_item */, const MatchedResultItem& /* matched_result_item */) {
    return;
  }
};

typedef struct _StaticLinkBaseService_load_db_task_args__isset {
  _StaticLinkBaseService_load_db_task_args__isset() : task_id(false), is_add_task(false) {}
  bool task_id;
  bool is_add_task;
} _StaticLinkBaseService_load_db_task_args__isset;

class StaticLinkBaseService_load_db_task_args {
 public:

  StaticLinkBaseService_load_db_task_args() : task_id(0), is_add_task(0) {
  }

  virtual ~StaticLinkBaseService_load_db_task_args() throw() {}

  int32_t task_id;
  bool is_add_task;

  _StaticLinkBaseService_load_db_task_args__isset __isset;

  void __set_task_id(const int32_t val) {
    task_id = val;
  }

  void __set_is_add_task(const bool val) {
    is_add_task = val;
  }

  bool operator == (const StaticLinkBaseService_load_db_task_args & rhs) const
  {
    if (!(task_id == rhs.task_id))
      return false;
    if (!(is_add_task == rhs.is_add_task))
      return false;
    return true;
  }
  bool operator != (const StaticLinkBaseService_load_db_task_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StaticLinkBaseService_load_db_task_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StaticLinkBaseService_load_db_task_pargs {
 public:


  virtual ~StaticLinkBaseService_load_db_task_pargs() throw() {}

  const int32_t* task_id;
  const bool* is_add_task;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StaticLinkBaseService_load_db_task_result {
 public:

  StaticLinkBaseService_load_db_task_result() {
  }

  virtual ~StaticLinkBaseService_load_db_task_result() throw() {}


  bool operator == (const StaticLinkBaseService_load_db_task_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const StaticLinkBaseService_load_db_task_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StaticLinkBaseService_load_db_task_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StaticLinkBaseService_load_db_task_presult {
 public:


  virtual ~StaticLinkBaseService_load_db_task_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _StaticLinkBaseService_load_mongodb_task_args__isset {
  _StaticLinkBaseService_load_mongodb_task_args__isset() : task_id(false), is_add_task(false) {}
  bool task_id;
  bool is_add_task;
} _StaticLinkBaseService_load_mongodb_task_args__isset;

class StaticLinkBaseService_load_mongodb_task_args {
 public:

  StaticLinkBaseService_load_mongodb_task_args() : task_id(0), is_add_task(0) {
  }

  virtual ~StaticLinkBaseService_load_mongodb_task_args() throw() {}

  int32_t task_id;
  bool is_add_task;

  _StaticLinkBaseService_load_mongodb_task_args__isset __isset;

  void __set_task_id(const int32_t val) {
    task_id = val;
  }

  void __set_is_add_task(const bool val) {
    is_add_task = val;
  }

  bool operator == (const StaticLinkBaseService_load_mongodb_task_args & rhs) const
  {
    if (!(task_id == rhs.task_id))
      return false;
    if (!(is_add_task == rhs.is_add_task))
      return false;
    return true;
  }
  bool operator != (const StaticLinkBaseService_load_mongodb_task_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StaticLinkBaseService_load_mongodb_task_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StaticLinkBaseService_load_mongodb_task_pargs {
 public:


  virtual ~StaticLinkBaseService_load_mongodb_task_pargs() throw() {}

  const int32_t* task_id;
  const bool* is_add_task;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StaticLinkBaseService_load_mongodb_task_result {
 public:

  StaticLinkBaseService_load_mongodb_task_result() {
  }

  virtual ~StaticLinkBaseService_load_mongodb_task_result() throw() {}


  bool operator == (const StaticLinkBaseService_load_mongodb_task_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const StaticLinkBaseService_load_mongodb_task_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StaticLinkBaseService_load_mongodb_task_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StaticLinkBaseService_load_mongodb_task_presult {
 public:


  virtual ~StaticLinkBaseService_load_mongodb_task_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class StaticLinkBaseService_get_download_task_args {
 public:

  StaticLinkBaseService_get_download_task_args() {
  }

  virtual ~StaticLinkBaseService_get_download_task_args() throw() {}


  bool operator == (const StaticLinkBaseService_get_download_task_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const StaticLinkBaseService_get_download_task_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StaticLinkBaseService_get_download_task_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StaticLinkBaseService_get_download_task_pargs {
 public:


  virtual ~StaticLinkBaseService_get_download_task_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _StaticLinkBaseService_get_download_task_result__isset {
  _StaticLinkBaseService_get_download_task_result__isset() : success(false) {}
  bool success;
} _StaticLinkBaseService_get_download_task_result__isset;

class StaticLinkBaseService_get_download_task_result {
 public:

  StaticLinkBaseService_get_download_task_result() {
  }

  virtual ~StaticLinkBaseService_get_download_task_result() throw() {}

  std::vector<DownloadTask>  success;

  _StaticLinkBaseService_get_download_task_result__isset __isset;

  void __set_success(const std::vector<DownloadTask> & val) {
    success = val;
  }

  bool operator == (const StaticLinkBaseService_get_download_task_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const StaticLinkBaseService_get_download_task_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StaticLinkBaseService_get_download_task_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _StaticLinkBaseService_get_download_task_presult__isset {
  _StaticLinkBaseService_get_download_task_presult__isset() : success(false) {}
  bool success;
} _StaticLinkBaseService_get_download_task_presult__isset;

class StaticLinkBaseService_get_download_task_presult {
 public:


  virtual ~StaticLinkBaseService_get_download_task_presult() throw() {}

  std::vector<DownloadTask> * success;

  _StaticLinkBaseService_get_download_task_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class StaticLinkBaseService_get_extract_task_args {
 public:

  StaticLinkBaseService_get_extract_task_args() {
  }

  virtual ~StaticLinkBaseService_get_extract_task_args() throw() {}


  bool operator == (const StaticLinkBaseService_get_extract_task_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const StaticLinkBaseService_get_extract_task_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StaticLinkBaseService_get_extract_task_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StaticLinkBaseService_get_extract_task_pargs {
 public:


  virtual ~StaticLinkBaseService_get_extract_task_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _StaticLinkBaseService_get_extract_task_result__isset {
  _StaticLinkBaseService_get_extract_task_result__isset() : success(false) {}
  bool success;
} _StaticLinkBaseService_get_extract_task_result__isset;

class StaticLinkBaseService_get_extract_task_result {
 public:

  StaticLinkBaseService_get_extract_task_result() {
  }

  virtual ~StaticLinkBaseService_get_extract_task_result() throw() {}

  std::vector<ExtractItem>  success;

  _StaticLinkBaseService_get_extract_task_result__isset __isset;

  void __set_success(const std::vector<ExtractItem> & val) {
    success = val;
  }

  bool operator == (const StaticLinkBaseService_get_extract_task_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const StaticLinkBaseService_get_extract_task_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StaticLinkBaseService_get_extract_task_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _StaticLinkBaseService_get_extract_task_presult__isset {
  _StaticLinkBaseService_get_extract_task_presult__isset() : success(false) {}
  bool success;
} _StaticLinkBaseService_get_extract_task_presult__isset;

class StaticLinkBaseService_get_extract_task_presult {
 public:


  virtual ~StaticLinkBaseService_get_extract_task_presult() throw() {}

  std::vector<ExtractItem> * success;

  _StaticLinkBaseService_get_extract_task_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class StaticLinkBaseService_get_one_extract_task_args {
 public:

  StaticLinkBaseService_get_one_extract_task_args() {
  }

  virtual ~StaticLinkBaseService_get_one_extract_task_args() throw() {}


  bool operator == (const StaticLinkBaseService_get_one_extract_task_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const StaticLinkBaseService_get_one_extract_task_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StaticLinkBaseService_get_one_extract_task_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StaticLinkBaseService_get_one_extract_task_pargs {
 public:


  virtual ~StaticLinkBaseService_get_one_extract_task_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _StaticLinkBaseService_get_one_extract_task_result__isset {
  _StaticLinkBaseService_get_one_extract_task_result__isset() : success(false) {}
  bool success;
} _StaticLinkBaseService_get_one_extract_task_result__isset;

class StaticLinkBaseService_get_one_extract_task_result {
 public:

  StaticLinkBaseService_get_one_extract_task_result() {
  }

  virtual ~StaticLinkBaseService_get_one_extract_task_result() throw() {}

  ExtractItem success;

  _StaticLinkBaseService_get_one_extract_task_result__isset __isset;

  void __set_success(const ExtractItem& val) {
    success = val;
  }

  bool operator == (const StaticLinkBaseService_get_one_extract_task_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const StaticLinkBaseService_get_one_extract_task_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StaticLinkBaseService_get_one_extract_task_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _StaticLinkBaseService_get_one_extract_task_presult__isset {
  _StaticLinkBaseService_get_one_extract_task_presult__isset() : success(false) {}
  bool success;
} _StaticLinkBaseService_get_one_extract_task_presult__isset;

class StaticLinkBaseService_get_one_extract_task_presult {
 public:


  virtual ~StaticLinkBaseService_get_one_extract_task_presult() throw() {}

  ExtractItem* success;

  _StaticLinkBaseService_get_one_extract_task_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _StaticLinkBaseService_upload_download_task_args__isset {
  _StaticLinkBaseService_upload_download_task_args__isset() : downloaded_body_item(false) {}
  bool downloaded_body_item;
} _StaticLinkBaseService_upload_download_task_args__isset;

class StaticLinkBaseService_upload_download_task_args {
 public:

  StaticLinkBaseService_upload_download_task_args() {
  }

  virtual ~StaticLinkBaseService_upload_download_task_args() throw() {}

  DownloadedBodyItem downloaded_body_item;

  _StaticLinkBaseService_upload_download_task_args__isset __isset;

  void __set_downloaded_body_item(const DownloadedBodyItem& val) {
    downloaded_body_item = val;
  }

  bool operator == (const StaticLinkBaseService_upload_download_task_args & rhs) const
  {
    if (!(downloaded_body_item == rhs.downloaded_body_item))
      return false;
    return true;
  }
  bool operator != (const StaticLinkBaseService_upload_download_task_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StaticLinkBaseService_upload_download_task_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StaticLinkBaseService_upload_download_task_pargs {
 public:


  virtual ~StaticLinkBaseService_upload_download_task_pargs() throw() {}

  const DownloadedBodyItem* downloaded_body_item;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StaticLinkBaseService_upload_download_task_result {
 public:

  StaticLinkBaseService_upload_download_task_result() {
  }

  virtual ~StaticLinkBaseService_upload_download_task_result() throw() {}


  bool operator == (const StaticLinkBaseService_upload_download_task_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const StaticLinkBaseService_upload_download_task_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StaticLinkBaseService_upload_download_task_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StaticLinkBaseService_upload_download_task_presult {
 public:


  virtual ~StaticLinkBaseService_upload_download_task_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _StaticLinkBaseService_upload_extract_task_args__isset {
  _StaticLinkBaseService_upload_extract_task_args__isset() : extract_item(false), matched_result_item(false) {}
  bool extract_item;
  bool matched_result_item;
} _StaticLinkBaseService_upload_extract_task_args__isset;

class StaticLinkBaseService_upload_extract_task_args {
 public:

  StaticLinkBaseService_upload_extract_task_args() {
  }

  virtual ~StaticLinkBaseService_upload_extract_task_args() throw() {}

  ExtractItem extract_item;
  MatchedResultItem matched_result_item;

  _StaticLinkBaseService_upload_extract_task_args__isset __isset;

  void __set_extract_item(const ExtractItem& val) {
    extract_item = val;
  }

  void __set_matched_result_item(const MatchedResultItem& val) {
    matched_result_item = val;
  }

  bool operator == (const StaticLinkBaseService_upload_extract_task_args & rhs) const
  {
    if (!(extract_item == rhs.extract_item))
      return false;
    if (!(matched_result_item == rhs.matched_result_item))
      return false;
    return true;
  }
  bool operator != (const StaticLinkBaseService_upload_extract_task_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StaticLinkBaseService_upload_extract_task_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StaticLinkBaseService_upload_extract_task_pargs {
 public:


  virtual ~StaticLinkBaseService_upload_extract_task_pargs() throw() {}

  const ExtractItem* extract_item;
  const MatchedResultItem* matched_result_item;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StaticLinkBaseService_upload_extract_task_result {
 public:

  StaticLinkBaseService_upload_extract_task_result() {
  }

  virtual ~StaticLinkBaseService_upload_extract_task_result() throw() {}


  bool operator == (const StaticLinkBaseService_upload_extract_task_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const StaticLinkBaseService_upload_extract_task_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StaticLinkBaseService_upload_extract_task_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StaticLinkBaseService_upload_extract_task_presult {
 public:


  virtual ~StaticLinkBaseService_upload_extract_task_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class StaticLinkBaseServiceClient : virtual public StaticLinkBaseServiceIf {
 public:
  StaticLinkBaseServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  StaticLinkBaseServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void load_db_task(const int32_t task_id, const bool is_add_task);
  void send_load_db_task(const int32_t task_id, const bool is_add_task);
  void recv_load_db_task();
  void load_mongodb_task(const int32_t task_id, const bool is_add_task);
  void send_load_mongodb_task(const int32_t task_id, const bool is_add_task);
  void recv_load_mongodb_task();
  void get_download_task(std::vector<DownloadTask> & _return);
  void send_get_download_task();
  void recv_get_download_task(std::vector<DownloadTask> & _return);
  void get_extract_task(std::vector<ExtractItem> & _return);
  void send_get_extract_task();
  void recv_get_extract_task(std::vector<ExtractItem> & _return);
  void get_one_extract_task(ExtractItem& _return);
  void send_get_one_extract_task();
  void recv_get_one_extract_task(ExtractItem& _return);
  void upload_download_task(const DownloadedBodyItem& downloaded_body_item);
  void send_upload_download_task(const DownloadedBodyItem& downloaded_body_item);
  void recv_upload_download_task();
  void upload_extract_task(const ExtractItem& extract_item, const MatchedResultItem& matched_result_item);
  void send_upload_extract_task(const ExtractItem& extract_item, const MatchedResultItem& matched_result_item);
  void recv_upload_extract_task();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class StaticLinkBaseServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<StaticLinkBaseServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (StaticLinkBaseServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_load_db_task(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_load_mongodb_task(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_download_task(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_extract_task(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_one_extract_task(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_upload_download_task(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_upload_extract_task(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  StaticLinkBaseServiceProcessor(boost::shared_ptr<StaticLinkBaseServiceIf> iface) :
    iface_(iface) {
    processMap_["load_db_task"] = &StaticLinkBaseServiceProcessor::process_load_db_task;
    processMap_["load_mongodb_task"] = &StaticLinkBaseServiceProcessor::process_load_mongodb_task;
    processMap_["get_download_task"] = &StaticLinkBaseServiceProcessor::process_get_download_task;
    processMap_["get_extract_task"] = &StaticLinkBaseServiceProcessor::process_get_extract_task;
    processMap_["get_one_extract_task"] = &StaticLinkBaseServiceProcessor::process_get_one_extract_task;
    processMap_["upload_download_task"] = &StaticLinkBaseServiceProcessor::process_upload_download_task;
    processMap_["upload_extract_task"] = &StaticLinkBaseServiceProcessor::process_upload_extract_task;
  }

  virtual ~StaticLinkBaseServiceProcessor() {}
};

class StaticLinkBaseServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  StaticLinkBaseServiceProcessorFactory(const ::boost::shared_ptr< StaticLinkBaseServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< StaticLinkBaseServiceIfFactory > handlerFactory_;
};

class StaticLinkBaseServiceMultiface : virtual public StaticLinkBaseServiceIf {
 public:
  StaticLinkBaseServiceMultiface(std::vector<boost::shared_ptr<StaticLinkBaseServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~StaticLinkBaseServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<StaticLinkBaseServiceIf> > ifaces_;
  StaticLinkBaseServiceMultiface() {}
  void add(boost::shared_ptr<StaticLinkBaseServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void load_db_task(const int32_t task_id, const bool is_add_task) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->load_db_task(task_id, is_add_task);
    }
    ifaces_[i]->load_db_task(task_id, is_add_task);
  }

  void load_mongodb_task(const int32_t task_id, const bool is_add_task) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->load_mongodb_task(task_id, is_add_task);
    }
    ifaces_[i]->load_mongodb_task(task_id, is_add_task);
  }

  void get_download_task(std::vector<DownloadTask> & _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get_download_task(_return);
    }
    ifaces_[i]->get_download_task(_return);
    return;
  }

  void get_extract_task(std::vector<ExtractItem> & _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get_extract_task(_return);
    }
    ifaces_[i]->get_extract_task(_return);
    return;
  }

  void get_one_extract_task(ExtractItem& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get_one_extract_task(_return);
    }
    ifaces_[i]->get_one_extract_task(_return);
    return;
  }

  void upload_download_task(const DownloadedBodyItem& downloaded_body_item) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->upload_download_task(downloaded_body_item);
    }
    ifaces_[i]->upload_download_task(downloaded_body_item);
  }

  void upload_extract_task(const ExtractItem& extract_item, const MatchedResultItem& matched_result_item) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->upload_extract_task(extract_item, matched_result_item);
    }
    ifaces_[i]->upload_extract_task(extract_item, matched_result_item);
  }

};



#endif
