/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef conf_crawler_CONSTANTS_H
#define conf_crawler_CONSTANTS_H

#include "conf_crawler_types.h"



class conf_crawlerConstants {
 public:
  conf_crawlerConstants();

};

extern const conf_crawlerConstants g_conf_crawler_constants;



#endif
