// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "CoverageService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class CoverageServiceHandler : virtual public CoverageServiceIf {
 public:
  CoverageServiceHandler() {
    // Your initialization goes here
  }

  void get_download_task(std::vector<DownloadTask> & _return) {
    // Your implementation goes here
    printf("get_download_task\n");
  }

  void upload_download_task(const DownloadedBodyItem& downloaded_body_item) {
    // Your implementation goes here
    printf("upload_download_task\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<CoverageServiceHandler> handler(new CoverageServiceHandler());
  shared_ptr<TProcessor> processor(new CoverageServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

