/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef DCService_H
#define DCService_H

#include <thrift/TDispatchProcessor.h>
#include "conf_crawler_types.h"



class DCServiceIf {
 public:
  virtual ~DCServiceIf() {}
  virtual void get_download_task(std::vector<DownloadTask> & _return, const DownloaderType::type downloader_type) = 0;
  virtual void push_download_task(const DownloadTask& download_task) = 0;
  virtual void upload_download_task(const DownloadedBodyItem& downloaded_body_item) = 0;
};

class DCServiceIfFactory {
 public:
  typedef DCServiceIf Handler;

  virtual ~DCServiceIfFactory() {}

  virtual DCServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(DCServiceIf* /* handler */) = 0;
};

class DCServiceIfSingletonFactory : virtual public DCServiceIfFactory {
 public:
  DCServiceIfSingletonFactory(const boost::shared_ptr<DCServiceIf>& iface) : iface_(iface) {}
  virtual ~DCServiceIfSingletonFactory() {}

  virtual DCServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(DCServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<DCServiceIf> iface_;
};

class DCServiceNull : virtual public DCServiceIf {
 public:
  virtual ~DCServiceNull() {}
  void get_download_task(std::vector<DownloadTask> & /* _return */, const DownloaderType::type /* downloader_type */) {
    return;
  }
  void push_download_task(const DownloadTask& /* download_task */) {
    return;
  }
  void upload_download_task(const DownloadedBodyItem& /* downloaded_body_item */) {
    return;
  }
};

typedef struct _DCService_get_download_task_args__isset {
  _DCService_get_download_task_args__isset() : downloader_type(false) {}
  bool downloader_type;
} _DCService_get_download_task_args__isset;

class DCService_get_download_task_args {
 public:

  DCService_get_download_task_args() : downloader_type((DownloaderType::type)0) {
  }

  virtual ~DCService_get_download_task_args() throw() {}

  DownloaderType::type downloader_type;

  _DCService_get_download_task_args__isset __isset;

  void __set_downloader_type(const DownloaderType::type val) {
    downloader_type = val;
  }

  bool operator == (const DCService_get_download_task_args & rhs) const
  {
    if (!(downloader_type == rhs.downloader_type))
      return false;
    return true;
  }
  bool operator != (const DCService_get_download_task_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DCService_get_download_task_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DCService_get_download_task_pargs {
 public:


  virtual ~DCService_get_download_task_pargs() throw() {}

  const DownloaderType::type* downloader_type;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _DCService_get_download_task_result__isset {
  _DCService_get_download_task_result__isset() : success(false) {}
  bool success;
} _DCService_get_download_task_result__isset;

class DCService_get_download_task_result {
 public:

  DCService_get_download_task_result() {
  }

  virtual ~DCService_get_download_task_result() throw() {}

  std::vector<DownloadTask>  success;

  _DCService_get_download_task_result__isset __isset;

  void __set_success(const std::vector<DownloadTask> & val) {
    success = val;
  }

  bool operator == (const DCService_get_download_task_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const DCService_get_download_task_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DCService_get_download_task_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _DCService_get_download_task_presult__isset {
  _DCService_get_download_task_presult__isset() : success(false) {}
  bool success;
} _DCService_get_download_task_presult__isset;

class DCService_get_download_task_presult {
 public:


  virtual ~DCService_get_download_task_presult() throw() {}

  std::vector<DownloadTask> * success;

  _DCService_get_download_task_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _DCService_push_download_task_args__isset {
  _DCService_push_download_task_args__isset() : download_task(false) {}
  bool download_task;
} _DCService_push_download_task_args__isset;

class DCService_push_download_task_args {
 public:

  DCService_push_download_task_args() {
  }

  virtual ~DCService_push_download_task_args() throw() {}

  DownloadTask download_task;

  _DCService_push_download_task_args__isset __isset;

  void __set_download_task(const DownloadTask& val) {
    download_task = val;
  }

  bool operator == (const DCService_push_download_task_args & rhs) const
  {
    if (!(download_task == rhs.download_task))
      return false;
    return true;
  }
  bool operator != (const DCService_push_download_task_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DCService_push_download_task_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DCService_push_download_task_pargs {
 public:


  virtual ~DCService_push_download_task_pargs() throw() {}

  const DownloadTask* download_task;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DCService_push_download_task_result {
 public:

  DCService_push_download_task_result() {
  }

  virtual ~DCService_push_download_task_result() throw() {}


  bool operator == (const DCService_push_download_task_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const DCService_push_download_task_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DCService_push_download_task_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DCService_push_download_task_presult {
 public:


  virtual ~DCService_push_download_task_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _DCService_upload_download_task_args__isset {
  _DCService_upload_download_task_args__isset() : downloaded_body_item(false) {}
  bool downloaded_body_item;
} _DCService_upload_download_task_args__isset;

class DCService_upload_download_task_args {
 public:

  DCService_upload_download_task_args() {
  }

  virtual ~DCService_upload_download_task_args() throw() {}

  DownloadedBodyItem downloaded_body_item;

  _DCService_upload_download_task_args__isset __isset;

  void __set_downloaded_body_item(const DownloadedBodyItem& val) {
    downloaded_body_item = val;
  }

  bool operator == (const DCService_upload_download_task_args & rhs) const
  {
    if (!(downloaded_body_item == rhs.downloaded_body_item))
      return false;
    return true;
  }
  bool operator != (const DCService_upload_download_task_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DCService_upload_download_task_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DCService_upload_download_task_pargs {
 public:


  virtual ~DCService_upload_download_task_pargs() throw() {}

  const DownloadedBodyItem* downloaded_body_item;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DCService_upload_download_task_result {
 public:

  DCService_upload_download_task_result() {
  }

  virtual ~DCService_upload_download_task_result() throw() {}


  bool operator == (const DCService_upload_download_task_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const DCService_upload_download_task_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DCService_upload_download_task_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DCService_upload_download_task_presult {
 public:


  virtual ~DCService_upload_download_task_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class DCServiceClient : virtual public DCServiceIf {
 public:
  DCServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  DCServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void get_download_task(std::vector<DownloadTask> & _return, const DownloaderType::type downloader_type);
  void send_get_download_task(const DownloaderType::type downloader_type);
  void recv_get_download_task(std::vector<DownloadTask> & _return);
  void push_download_task(const DownloadTask& download_task);
  void send_push_download_task(const DownloadTask& download_task);
  void recv_push_download_task();
  void upload_download_task(const DownloadedBodyItem& downloaded_body_item);
  void send_upload_download_task(const DownloadedBodyItem& downloaded_body_item);
  void recv_upload_download_task();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class DCServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<DCServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (DCServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_get_download_task(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_push_download_task(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_upload_download_task(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  DCServiceProcessor(boost::shared_ptr<DCServiceIf> iface) :
    iface_(iface) {
    processMap_["get_download_task"] = &DCServiceProcessor::process_get_download_task;
    processMap_["push_download_task"] = &DCServiceProcessor::process_push_download_task;
    processMap_["upload_download_task"] = &DCServiceProcessor::process_upload_download_task;
  }

  virtual ~DCServiceProcessor() {}
};

class DCServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  DCServiceProcessorFactory(const ::boost::shared_ptr< DCServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< DCServiceIfFactory > handlerFactory_;
};

class DCServiceMultiface : virtual public DCServiceIf {
 public:
  DCServiceMultiface(std::vector<boost::shared_ptr<DCServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~DCServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<DCServiceIf> > ifaces_;
  DCServiceMultiface() {}
  void add(boost::shared_ptr<DCServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void get_download_task(std::vector<DownloadTask> & _return, const DownloaderType::type downloader_type) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get_download_task(_return, downloader_type);
    }
    ifaces_[i]->get_download_task(_return, downloader_type);
    return;
  }

  void push_download_task(const DownloadTask& download_task) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->push_download_task(download_task);
    }
    ifaces_[i]->push_download_task(download_task);
  }

  void upload_download_task(const DownloadedBodyItem& downloaded_body_item) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->upload_download_task(downloaded_body_item);
    }
    ifaces_[i]->upload_download_task(downloaded_body_item);
  }

};



#endif
