// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "HeaderFieldsService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class HeaderFieldsServiceHandler : virtual public HeaderFieldsServiceIf {
 public:
  HeaderFieldsServiceHandler() {
    // Your initialization goes here
  }

  void get_header_fields(std::vector<std::string> & _return, const std::string& url, const int32_t depth) {
    // Your implementation goes here
    printf("get_header_fields\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<HeaderFieldsServiceHandler> handler(new HeaderFieldsServiceHandler());
  shared_ptr<TProcessor> processor(new HeaderFieldsServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

