test_scribe_client_ex:test_scribe_client_ex.cc
	g++ -I/usr/local/webserver/thrift/include/thrift/ -I/usr/local/webserver/boost_1_44_0/include/ -I../../../../../include/ -L../../../../../lib/ -L/usr/local/webserver/thrift/lib -L/usr/local/webserver/thrift/lib/ -L/usr/local/webserver/fb303/lib/ test_scribe_client_ex.cc -o test_scribe_client_ex -lthrift -lfb303 -lganji_util -lganji_util_scribe_log


test_multi_scribe_client_ex:test_multi_scribe_client_ex.cc
	g++ -I/usr/local/webserver/thrift/include/thrift/ -I/usr/local/webserver/boost_1_44_0/include/ -I../../../../../include/ -L../../../../../lib/ -L/usr/local/webserver/thrift/lib -L/usr/local/webserver/thrift/lib/ -L/usr/local/webserver/fb303/lib/ test_multi_scribe_client_ex.cc -o test_multi_scribe_client_ex -lthrift -lfb303 -lganji_util -lganji_util_scribe_log
