// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "CheckDeadlinkService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class CheckDeadlinkServiceHandler : virtual public CheckDeadlinkServiceIf {
 public:
  CheckDeadlinkServiceHandler() {
    // Your initialization goes here
  }

  bool is_dead_link(const std::string& url, const std::string& body) {
    // Your implementation goes here
    printf("is_dead_link\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<CheckDeadlinkServiceHandler> handler(new CheckDeadlinkServiceHandler());
  shared_ptr<TProcessor> processor(new CheckDeadlinkServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

