/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "conf_crawler_constants.h"



const conf_crawlerConstants g_conf_crawler_constants;

conf_crawlerConstants::conf_crawlerConstants() {
}



