// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ExtractorService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class ExtractorServiceHandler : virtual public ExtractorServiceIf {
 public:
  ExtractorServiceHandler() {
    // Your initialization goes here
  }

  int32_t load_template(const std::string& url_template, const TemplateType::type template_type) {
    // Your implementation goes here
    printf("load_template\n");
  }

  void unload_template(const std::string& url_template, const TemplateType::type template_type) {
    // Your implementation goes here
    printf("unload_template\n");
  }

  void extract_sync(MatchedResultItem& _return, const ExtractItem& extract_item) {
    // Your implementation goes here
    printf("extract_sync\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ExtractorServiceHandler> handler(new ExtractorServiceHandler());
  shared_ptr<TProcessor> processor(new ExtractorServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

